name: "PyPI"

on:
  push:
    tags:
      - "v*.*"

jobs:
  publish:
    name: "PyPI Publish"

    runs-on: "ubuntu-latest"

    environment:
      name: "pypi"
      url: "https://pypi.org/p/playwright-html-renderer"

    permissions:
      contents: "read"
      id-token: "write" # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"

      - name: "Setup Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"

      - name: "Cache Python Dependencies"
        uses: "actions/cache@v4"
        with:
          path: "~/.cache/pip"
          key: ${{ runner.os }}-publish-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-publish-pip-

      - name: "Install Python Dependencies"
        run: "pip install setuptools wheel twine"

      - name: "Build Python Package Distribution"
        run: "python setup.py sdist bdist_wheel"

      - name: "Publish Python Package Distributions to PyPI"
        uses: "pypa/gh-action-pypi-publish@release/v1"